// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bamwwxxgundbmoxtknkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhbXd3eHhndW5kYm1veHRrbmt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4Mzg5MzQsImV4cCI6MjA1NjQxNDkzNH0.sENiLs4M6-lWfjmPoA28ta8ma9mWS7MuKlwcYrABJwA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);