
// deno-lint-ignore-file no-explicit-any
import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  try {
    const { message, context, userType, userId, analysisId } = await req.json()

    if (!message) {
      return new Response(
        JSON.stringify({ error: 'No message provided' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Initialize Gemini API
    const apiKey = Deno.env.get('GEMINI_API_KEY')
    if (!apiKey) {
      return new Response(
        JSON.stringify({ error: 'API key not configured' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Create the Supabase client if we need to store the interaction
    const supabase = userId && analysisId ? createClient(
      Deno.env.get('SUPABASE_URL') as string,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') as string
    ) : null;

    // Call Gemini API
    console.log(`Processing chat request with Gemini AI...`)

    // Use the updated model: gemini-1.5-flash-latest
    const baseURL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent"
    const url = `${baseURL}?key=${apiKey}`

    // Prepare enhanced context with user type
    const enhancedContext = context ? 
      `${context}\n\nAdditional context: The user asking the question is a ${userType === 'doctor' ? 'healthcare professional (write in technical medical terms)' : 'patient (explain in simple terms that a non-medical person can understand)'}.\n\nUser: ${message}` 
      : message;

    // Prepare the request to Gemini
    const payload = {
      contents: [
        {
          parts: [
            { 
              text: enhancedContext
            }
          ]
        }
      ],
      generationConfig: {
        temperature: 0.7,
        maxOutputTokens: 800,
      }
    }

    console.log("Sending request to Gemini with model: gemini-1.5-flash-latest");

    // Call the Gemini API
    const response = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify(payload)
    })

    if (!response.ok) {
      const errorText = await response.text()
      console.error("Gemini API error:", errorText)
      throw new Error(`Gemini API error: ${response.status} ${errorText}`)
    }

    const data = await response.json()
    
    if (!data.candidates || data.candidates.length === 0) {
      throw new Error("No response generated by the model")
    }

    // Extract the response text
    const aiResponse = data.candidates[0].content.parts[0].text
    
    // Store the chat interaction if we have user ID and analysis ID
    if (userId && analysisId && supabase) {
      try {
        const { data: chatData, error: insertError } = await supabase
          .from('chat_interactions')
          .insert({
            user_id: userId,
            analysis_id: analysisId,
            user_message: message,
            ai_response: aiResponse
          })
        
        if (insertError) {
          console.error("Error storing chat interaction:", insertError)
        } else {
          console.log("Chat interaction stored successfully")
        }
      } catch (storageError) {
        console.error("Error storing chat:", storageError)
      }
    }

    // Return the AI response
    return new Response(
      JSON.stringify({ response: aiResponse }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )

  } catch (error) {
    console.error("Error processing chat:", error)
    return new Response(
      JSON.stringify({ error: `Failed to process the chat: ${error.message}` }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  }
})
